# Generated by Django 4.1 on 2023-10-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "credentials",
            "0003_userprofile_materials_alter_userprofile_account_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="materials",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="choice1",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="choice2",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="choice3",
            field=models.BooleanField(default=False),
        ),
    ]
