# Generated by Django 4.1 on 2023-10-05 07:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "credentials",
            "0004_remove_userprofile_materials_userprofile_choice1_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="choice1",
            new_name="checkbook",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="choice2",
            new_name="creditcard",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="choice3",
            new_name="debitcard",
        ),
    ]
