# Generated by Django 4.1 on 2023-10-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("credentials", "0005_rename_choice1_userprofile_checkbook_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="checkbook",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="creditcard",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="debitcard",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="materials",
            field=models.CharField(default="credit card", max_length=20),
        ),
    ]
